version: 2

models:
  - name: rakuten_products_raw
    description: Raw product data from Rakuten API stored as JSONB
    columns:
      - name: data
        description: Raw JSON data from Rakuten Product Search API
        tests:
          - not_null

      - name: loaded_at
        description: Timestamp when the data was loaded
        tests:
          - not_null
